name: prophecy_examples
description: ''
version: 0.0.1
author: nimbus@simpledatalabs.com
language: scala
buildSystem: maven
pipelines:
  pipelines/scd1_merge:
    name: scd1_merge
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-07-21 00:07:59'
    datasets:
      inputs:
      - 2348/datasets/customers_raw
      - 2348/datasets/customers_scd1
      outputs:
      - 2348/datasets/customers_scd1
    dependencies: {}
  pipelines/generate_incremental_data:
    name: generate_incremental_data
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-07-21 21:29:03'
    datasets:
      inputs:
      - 2348/datasets/customers_raw
      outputs: []
    dependencies: {}
  pipelines/generated_scd2_merge:
    name: generated_scd2_merge
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-07-21 23:10:57'
    datasets:
      inputs:
      - 2348/datasets/customers_raw
      - 2348/datasets/customers_scd2
      outputs:
      - 2348/datasets/customers_scd2
    dependencies: {}
  pipelines/config_tests:
    name: config_tests
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-07-21 03:37:30'
    datasets:
      inputs:
      - 2348/datasets/customers_raw
      outputs: []
    dependencies: {}
  pipelines/generated_scd1_merge:
    name: generated_scd1_merge
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-07-21 22:57:05'
    datasets:
      inputs:
      - 2348/datasets/customers_raw
      - 2348/datasets/customers_scd1
      outputs:
      - 2348/datasets/customers_scd1
    dependencies: {}
datasets:
  datasets/customers_raw:
    name: customers_raw
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-07-21 01:16:26'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-07-21 01:16:26'
  datasets/customers_scd1:
    name: customers_scd1
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-07-21 01:17:52'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-07-21 01:17:52'
  datasets/customers_scd2:
    name: customers_scd2
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-07-21 23:11:58'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-07-21 23:11:58'
templates: {}
jobs: {}
libraries: []
subgraphs:
  subgraphs/GenerateRandomIncrement:
    name: GenerateRandomIncrement
    description: ''
    author: nimbus@simpledatalabs.com
    language: scala
    createdAt: '2022-07-21 22:47:39'
dependencies: []
